- finance.html
initial filler added
```
git fetch -all
git checkout financialinterests
```
> Financial interests

- finance.html
- index.html
- newsFeed.html
- rap-sheet.html
added navigation element to bottom of executive summary page, and added main navigation to the top of every html page. 
to test code 
```
git checkout executiveSummaryNav
```
1. check code
1. click through links to make sure they all go where they should
> added navigation to all 4 html pages

- finance.html
hopefully this works... standard issue commands apply
> attempted change to formatting

- katyperry.css
updated fonts for h1-5 and p tags, updated sizes
```
git checkout globalstyles
```
> working on css

- execSumStyles.css
- index.html
added styles for the home page summary report
to test code 
run:
```
git checkout indexStyles
```
1. inspect code
1. analyze page for layout and styling issues
> added homepage styles

- katyperry.css
- newsFeed.css
- newsFeed.html
Mostly similar html, moved images around some. Check general look on page, can compare for continuity with other pages as they are updated. Check for unused CSS style elements. Think I got em all.
> added images, no style sheet yet

- finance.html
- index.html
- katyperry.css
- newsFeed.html
- rap-sheet.html
new font, updated p size in katyperry.css to 14px
```
git checkout mastercss
```
> updated font and increased p size to 14px'

- execSumStyles.css
- finance.html
- katyperry.css
- newsFeed.css
- rap-sheet.html
added main nav styles
to test 
```
git checkout mainNavUpdate
```
1. check code
1. load web page
1. check styles of page
> Main nav update

- katyperry.css
> Backgroundcss

- finance.html
- index.html
- newsFeed.html
- rap-sheet.html
> spelling corrections

- rap-sheet.html
added a class to twitter widgets to center them
to test 
```
git checkout fixTweets
```
1. load page
1. are tweets centered?
1. :ship: it
> added class to center tweet widgets

- katyperry.css
> added border and changed fonts

- execSumStyles.css
edited styles for homepage bottom navigation to make it easier to read.
to test
```
git checkout editSummaryNav
```
1. check code changed in execSumStyles.css
1. check readability of homepage bottom nav
> added styles to make bottom nav easier to read

- finance.css
- index.html
- katyperry.css
- newsFeed.html
```
git checkout list-background-style
```
Check: 
1. Imaged ratio on index.html
2. Peach backgrounds making text more legible
3. Minor text edits
> added background to ol, ul, p, and minor edits to text, image resize

- index.html
- removeDOM.js
added function to nuke dom
``` 
git checkout deleteDOM
```
1. test function in console
> added function to remove dom

- SummaryPrint.js
- summaryBuilder.js
added function to print executive summary
```
git checkout RMExecSumDocFrag
```
> added function to print summary

- index.html
- katyperry.css
> added styling to nav buttons

- buttons.js
- finance.css
- finproto.js
- index.html
- summaryBuilder.js
```
git checkout RMDomEditFunctions
```
> Rm dom edit functions

- elementFactory.js
- index.html
```
git checkout RMelementFactory
```
> R melement factory

- summaryBuilder.js
refactored summarybuilder.js to use element factory functions
```
git checkout RMExecSummaryRefactor
```
1. check to make sure summary still looks the same
> refactored code to use element factory functions

- buttons.js
fixed buttons no longer being interactive after clicking on one of them
```
git checkout RMButtonsDebugging
```
1. click on all the buttons
> fixed mouseover and mouseout functionality for nav buttons

- elementFactory.js
- finproto.js
check for proper refactor into functions. 
```
git checkout dprefactor
```
> Dprefactor

- rapsheet.js
- rapsheetprint.js
This version is presentable. Backgrounds to all sections. Twitter is missing. 
```git fetch --all
git pull origin prepresentation```
> presentable, no twitter

- katyperry.css
- rapsheet.js
- rapsheetprint.js
tweets are in text and are now readable
```git fetch --all
git pull origin pzc-readable-tweets```
> twitter text showing up

- index.html
```
git checkout RM-debugMysteryError
```
> Rm debug mystery error

- newsFeedJSDB.js
```
git checkout RM-debugNewsFeedFunction
```
> Rm debug news feed function
